// ============================================================
// Prompt library — everyday sentences contributors respond to.
// The Speak page rotates through these; Listen uses them too.
// Add freely — the more the better. Supabase auto-seeds from here.
// ============================================================

export const PROMPTS = {
  Igbo: [
    'Kedu ka ị dị taa?',
    'Gịnị ka ị na-eme ebe a?',
    'Biko nyere m aka ịkwọ ụgbọala a.',
    'Ahhịa dị ebe a na Tụzdee.',
    'Nne m na-esi ofe onugbu taa.',
    'Ebee ka ị zụrụ akwa a?',
    'Ọ dị m ụtọ ịhụ gị.',
    'Anyị ga-aga ụka n’ụtụtụ echi.',
    'Mmiri na-ezo nke ukwuu taa.',
    'Kpọọ m ekwe ntị n’abalị.',
    'Nwa nwoke ahụ na-agba bọọlụ n’ama.',
    'Biko rie nri gị tupu ọ jụọ oyi.',
    'Kedu ihe ị chọrọ ịzụta n’ahịa?',
    'Anyị ga-esi ebe a gaa Enugu.',
    'Oge ruru ka anyị laa n’ụlọ.',
    'Nna m na-arụ n’ugbo kwa ụtụtụ.',
    'Kedu aha onye isi obodo unu?',
    'Mụ na ndị enyi m ga-ezukọ n’uhuruchi.',
    'Aga m esi ofe akwu taa.',
    'Ị hụrụ nwaanyị ahụ na-ere akara?',
    'Ụzọ a dị ogologo ma dịkwa mma.',
    'Kedu mgbe ị ga-alaghachi ụlọ?',
    'Onye nkuzi anyị bịara n’oge taa.',
    'Anyị kwesịrị ịkwado oriri ngwa ngwa.',
    'Chere m ntakịrị, abịa n’azụ gị.',
    'Ọkụ latrik agbanyụọla kemgbe ụtụtụ.',
    'Nwata ahụ na-ebe akwa n’ihi agụụ.',
    'Ka anyị gaa mmiri tupu anyanwụ apụta.',
    'Onye ahụ na-ere azụ n’ọnụ ụzọ ahịa.',
    'Ihe a dị ọnụ ala karịa ka m cheburu.'
  ],
  Yoruba: [
    'Bawo ni ọjọ́ rẹ?',
    'Kíni o ń ṣe níbí?',
    'Jọ̀wọ́ ran mí lọ́wọ́ láti gbé nǹkan yìí.',
    'Ọjà ńlá wà nítòsí ilé wa.',
    'Ìyá mi ń se ẹ̀fọ́ rírò óní.',
    'Níbo ni o ti ra aṣọ yìí?',
    'Mo dúpẹ́ láti rí ẹ.',
    'A máa lọ sílé ẹ̀bí wa ní àárọ̀ ọ̀la.',
    'Òjò ń rọ̀ dáadáa lónìí.',
    'Pè mí lóòru ká lè sọ̀rọ̀.',
    'Ọmọkùnrin yẹn ń gá bọ́ọ̀lù ní pápá.',
    'Jẹ oúnjẹ rẹ kí ó tó tutù.',
    'Kíni o fẹ́ rà ní ọjà?',
    'A máa rìn ìrìnàjò lọ sí Ìbàdàn.',
    'Àkókò ti tó ká máa lọ sílé.',
    'Bàbá mi ń ṣiṣẹ́ ní oko ní gbogbo àárọ̀.',
    'Ta ni adarí ìlú yín?',
    'Èmi àti àwọn ọ̀rẹ́ mi máa pàdé ní ìrọ̀lẹ́.',
    'Mo máa se ẹ̀fọ́ rírò óní.',
    'Ṣé o rí obìnrin tó ń tà àkàrà yẹn?',
    'Ọ̀nà yìí gùn ṣùgbọ́n ó dára.',
    'Nígbà wo ni wà máa padà sílé?',
    'Olùkọ́ wa dé ní àkókò lónìí.',
    'A gbọ́dọ̀ ṣètò àsè náà kánkán.',
    'Dúró díẹ̀, mo ń bọ̀ lẹ́yìn rẹ.',
    'Iná mọ̀nàmọ́ná ti pa dá dá bíi òwúrò.',
    'Ọmọ náà ń sunkún nítorí ebi ń pa á.',
    'Ẹ jẹ́ ká lọ sí ojú ọ̀sùn kí ó tó dábọ̀ọ̀.',
    'Oníṣòwò ẹja ló wà ní ẹnu ọ̀nà ọjà.',
    'Èyí dín owo kù ju bí mo ti rò lọ.'
  ],
  Hausa: [
    'Yaya ake yi yau?',
    'Me kake yi a nan?',
    'Don Allah ka taimaka min ɗaukar wannan.',
    'Akwai babbar kasuwa kusa da gidanmu.',
    'Mahaifiyata tana dafa miyan kuka yau.',
    'Ina ka sayi wannan tufafin?',
    'Na yi farin cikin ganinka.',
    'Za mu tafi gari safiya.',
    'Ana ruwan sama sosai a yau.',
    'Ka kira ni daddare.',
    'Wancan yaron yana buga kwallon kafa a filin.',
    'Ka ci abincinka kafin ya yi sanyi.',
    'Me kake son saya a kasuwa?',
    'Za mu tafi Kano daga nan.',
    'Lokaci ya yi mu koma gida.',
    'Ubana yana aiki a gona kowace safiya.',
    'Waye shugaban garku?',
    'Ni da abokana za mu hadu yamma.',
    'Za ni dafa miyan kuka yau.',
    'Ka ga mace tana sayar da kosai can?',
    'Wannan hanya tana da tsayi amma tana da kyau.',
    'Yaushe za ka koma gida?',
    'Malaminmu ya zo a lokaci yau.',
    'Dole ne mu shirya bukuka nan take.',
    'Jira dan kadan, na zo a bayanka.',
    'Wutar lantarki ta kashe tun safiya.',
    'Yaron yana kuka saboda yunwa.',
    'Bari mu je rija kafin rana ta fito.',
    'Mai sayar da kifi yana kofar kasuwa.',
    'Wannan yana da arha fiye da yadda na zata.'
  ],
  Pidgin: [
    'How you dey today?',
    'Wetin you dey do here?',
    'Abeg help me carry this thing.',
    'Big market dey close to our house.',
    'My mama dey cook egusi soup today.',
    'Where you buy this cloth?',
    'I happy to see you.',
    'We go go church tomorrow morning.',
    'Rain dey fall well well today.',
    'Give me missed call for night.',
    'That boy dey play ball for field.',
    'Chop your food before e cold.',
    'Wetin you wan buy for market?',
    'We go waka go Enugu from here.',
    'Na time make we go house.',
    'My papa dey work for farm every morning.',
    'Who be the head of your village?',
    'Me and my friends go meet for evening.',
    'I go cook vegetable soup today.',
    'You see the woman wey dey sell akara there?',
    'This road long but e fine.',
    'Which time you go return house?',
    'Our teacher come on time today.',
    'We must arrange the party quick quick.',
    'Wait small, I dey come your back.',
    'Light don phas since morning.',
    'The pikin dey cry because hungry.',
    'Make we go well before sun come out.',
    'The fish seller dey for market gate.',
    'This one cheap pass how I think am.'
  ]
};

export const getPrompt = (language, seed = 0) => {
  const list = PROMPTS[language] || PROMPTS.Igbo;
  return list[Math.abs(seed) % list.length];
};

export const allPrompts = () => Object.entries(PROMPTS).flatMap(([language, rows]) => rows.map(text => ({ language, text })));
